apiVersion: v1
kind: Service
metadata:
  name: dev-node
  labels:
    app: dev-node
spec:
  selector:
    app: dev-node
  ports:
  - port: 3000
    targetPort: 3000
    name: web-dev
  - port: 22
    targetPort: 22
    name: sshd